#!/usr/bin/env bash

npx @bookshop/generate

# Rosey translations
npx rosey generate --source dist
npx rosey-cloudcannon-connector write-locales --source rosey --dest dist
mv ./dist ./_untranslated_site
npx rosey build --source _untranslated_site --dest dist --default-language en --default-language-at-root --exclusions "\.(html?)$"

# Pagefind search
npx -y pagefind --site dist